### ISSUE TITLE
Week One Spelling Errors

### ISSUE THREAD

**Issue by johncgenere** [hunter-college-ossd-spr19/HasanAbdullah31-weekly#1]
This issue is in reference to this [blog post](https://hunter-college-ossd-spr19.github.io/HasanAbdullah31-weekly/week01/).

In your Contributions section, you have two spelling errors:
- [Line 52](https://github.com/hunter-college-ossd-spr19/HasanAbdullah31-weekly/commit/1788110299066dbe651f792dab339c5411791d85#diff-1402d959a9fbfda3bcd1a76f7482ce5dR51)

"..and intuitive. It was also fun and rewarding to look through my **neighbourhood** (and other areas I frequently visit) on the map.." should be "..and intuitive. It was also fun and rewarding to look through my **neighborhood** (and other areas I frequently visit) on the map.."

- [Line 60](https://github.com/hunter-college-ossd-spr19/HasanAbdullah31-weekly/commit/1788110299066dbe651f792dab339c5411791d85#diff-1402d959a9fbfda3bcd1a76f7482ce5dR60)

"I added info about my **favourite** deli, which is also in my area (name and hours)" should be "I added info about my **favorite** deli, which is also in my area (name and hours)"

**Comment by HasanAbdullah31** [comment]
Those are the British spellings, which are correct as well. If you're curious, you can read about it here: https://english.stackexchange.com/questions/7866/ou-versus-o-in-spelling-words-like-color-colour
or here https://www.grammarly.com/blog/favorite-favourite/
